# Generated by Django 4.2.26 on 2025-11-15 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backtest_runner', '0002_angelonekey_alter_runrequest_api_key_delete_apikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=100)),
                ('input_filename', models.CharField(max_length=255)),
                ('events_csv', models.CharField(max_length=255)),
                ('trades_csv', models.CharField(max_length=255)),
                ('pnl_csv', models.CharField(max_length=255)),
                ('balance_png', models.CharField(max_length=255)),
                ('status', models.CharField(default='completed', max_length=30)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtest_runner.angelonekey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
