# Generated by Django 4.2.26 on 2026-01-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trading_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
