# Generated by Django 4.2.2 on 2024-08-27 18:18

from django.db import migrations
import os
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@gmail.com')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'Admin@312')

    if not User.objects.filter(username=username).exists():
        User.objects.create_superuser(username=username, email=email, password=password)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_trading_enabled'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]