# Generated by Django 4.2.26 on 2025-11-14 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backtest_runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngelOneKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('totp_secret', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=200)),
                ('jwt_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('feed_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='runrequest',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtest_runner.angelonekey'),
        ),
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
