# Generated by Django 4.2.26 on 2025-11-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_runner', '0002_angelonekey_alter_runrequest_api_key_delete_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runrequest',
            name='balance_png',
        ),
        migrations.RemoveField(
            model_name='runrequest',
            name='events_csv',
        ),
        migrations.RemoveField(
            model_name='runrequest',
            name='input_filename',
        ),
        migrations.RemoveField(
            model_name='runrequest',
            name='pnl_csv',
        ),
        migrations.RemoveField(
            model_name='runrequest',
            name='trades_csv',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='file_path',
        ),
        migrations.AddField(
            model_name='runrequest',
            name='results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='breakout_buffer',
            field=models.FloatField(default=0.0012),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='ema_long',
            field=models.IntegerField(default=78),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='ema_short',
            field=models.IntegerField(default=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='exchange',
            field=models.CharField(default='MCX', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='fixed_sl_pct',
            field=models.FloatField(default=0.015),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='margin_factor',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='strategy',
            name='point_value',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='symbol',
            field=models.CharField(default='SILVERM', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='strategy',
            name='trail_sl_pct',
            field=models.FloatField(default=0.025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
