# Generated by Django 4.2.26 on 2026-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_runner', '0003_remove_runrequest_balance_png_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='trading_symbol',
            field=models.CharField(blank=True, help_text='e.g. SILVERM30APR26FUT', max_length=50, null=True),
        ),
    ]
