# Generated by Django 4.2.26 on 2026-04-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtest_runner', '0004_strategy_trading_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='product_type',
            field=models.CharField(choices=[('INTRADAY', 'Intraday (INT)'), ('CARRYFORWARD', 'Carry Forward (CF)'), ('DELIVERY', 'Delivery')], default='INTRADAY', help_text='INT = Intraday, CF = Carry Forward. Used for live margin calculation.', max_length=20),
        ),
    ]
