# Generated by Django 4.2.26 on 2025-12-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveTick',
        ),
    ]
