# Generated by Django 4.2.26 on 2025-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('live_trading', '0002_delete_livetick'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('ltp', models.FloatField()),
                ('exchange_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
