# Generated by Django 4.2.26 on 2025-12-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0004_livecandle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecandle',
            name='token',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='livetick',
            name='token',
            field=models.CharField(max_length=32),
        ),
    ]
