# Generated by Django 4.2.26 on 2025-12-07 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_trading', '0005_alter_livecandle_token_alter_livetick_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livecandle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='livecandle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livetick',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livecandle',
            name='token',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='livetick',
            name='token',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='livecandle',
            unique_together={('user', 'token', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='livetick',
            index=models.Index(fields=['user', 'token', 'exchange_timestamp'], name='live_tradin_user_id_007146_idx'),
        ),
    ]
