# Generated by Django 4.2.26 on 2025-12-15 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_trading', '0006_alter_livecandle_unique_together_livecandle_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_streak', models.IntegerField(default=0)),
                ('loss_streak', models.IntegerField(default=0)),
                ('trades_today', models.IntegerField(default=0)),
                ('last_trade_day', models.DateField(blank=True, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('LONG', 'LONG'), ('SHORT', 'SHORT')], max_length=5)),
                ('entry_price', models.FloatField()),
                ('lots', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('fixed_sl', models.FloatField()),
                ('trailing_sl', models.FloatField()),
                ('is_open', models.BooleanField(default=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('exit_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
