# Generated by Django 4.2.26 on 2026-01-22 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_trading', '0007_tradestats_liveposition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='livecandle',
            unique_together={('user', 'token', 'start_time', 'interval')},
        ),
    ]
