# Generated by Django 4.2.26 on 2026-03-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_trading', '0008_alter_livecandle_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradestats',
            old_name='loss_streak',
            new_name='boost_count',
        ),
        migrations.RenameField(
            model_name='tradestats',
            old_name='win_streak',
            new_name='losses',
        ),
        migrations.AddField(
            model_name='tradestats',
            name='boost_next_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradestats',
            name='pending_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tradestats',
            name='position_size',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tradestats',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
